GameStates = {
  WAITING_FOR_OPPONENT: "WAITING_FOR_OPPONENT",
  PLACE_SHIPS: "PLACE_SHIPS",
  WAIT_FOR_ENEMY_SHIPS: "WAIT_FOR_ENEMY_SHIPS",
  SHOOT: "SHOOT",
  WAIT_FOR_ENEMY_SHOT: "WAIT_FOR_ENEMY_SHOT" 
}

module.exports = GameStates;
