const OrganConstants = {
  KEY_PRESSED: "KEY_PRESSED",
  KEY_RELEASED: "KEY_RELEASED",
  GROUP_UPDATE: "GROUP_UPDATE",
  RECORD_PRESSED: "RECORD_PRESSED",
  PLAY_PRESSED: "PLAY_PRESSED",
  CREATE_TRACK: "CREATE_TRACK",
  ADD_TRACK: "ADD_TRACK",
  RESET_TRACKS: "RESET_TRACKS",
  DELETE_TRACK: "DELETE_TRACK"
};

module.exports = OrganConstants;
