
export const RECEIVE_BENCHES = "RECEIVE_BENCHES";
export const RECEIVE_BENCH = "RECEIVE_BENCH";
export const REQUEST_BENCHES = "REQUEST_BENCHES";
export const REQUEST_BENCH = "REQUEST_BENCH";
export const CREATE_BENCH = "CREATE_BENCH";
export const CREATE_REVIEW = "CREATE_REVIEW";
